
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LESS_TE = 27;
  public static final int SCIENTIFIC_LITERAL = 54;
  public static final int POW = 45;
  public static final int STRING_LITERAL = 57;
  public static final int CHAR_LITERAL = 56;
  public static final int INDEX_OPEN = 36;
  public static final int CHAR_T = 5;
  public static final int CASE = 15;
  public static final int BOOL_T = 4;
  public static final int MINUS = 41;
  public static final int TILDE = 30;
  public static final int NOT = 50;
  public static final int AND = 48;
  public static final int EMPTY_T = 9;
  public static final int PIPE_R = 33;
  public static final int OR = 49;
  public static final int COMMA = 39;
  public static final int BANG = 38;
  public static final int PIPE_L = 32;
  public static final int INC = 46;
  public static final int DIV = 43;
  public static final int PLUS = 40;
  public static final int INT_T = 2;
  public static final int ASSIGN = 31;
  public static final int MAIN = 23;
  public static final int IF = 10;
  public static final int EOF = 0;
  public static final int RETURN = 17;
  public static final int EQUAL = 24;
  public static final int GREATHER_TE = 29;
  public static final int TRUE = 21;
  public static final int error = 1;
  public static final int MOD = 44;
  public static final int CIN = 19;
  public static final int INDEX_CLOSE = 37;
  public static final int BLOCK_CLOSE = 35;
  public static final int BREAK = 18;
  public static final int SWITCH = 14;
  public static final int TIMES = 42;
  public static final int SCIENTIFIC_T = 7;
  public static final int FRACTION_LITERAL = 55;
  public static final int FRAC_T = 8;
  public static final int ELSE = 11;
  public static final int COUT = 20;
  public static final int N_EQUAL = 25;
  public static final int WHILE = 13;
  public static final int DEFAULT = 16;
  public static final int GREATHER_T = 28;
  public static final int FLOAT_T = 3;
  public static final int DEC = 47;
  public static final int FLOAT_LITERAL = 53;
  public static final int FALSE = 22;
  public static final int LESS_T = 26;
  public static final int BLOCK_OPEN = 34;
  public static final int STRING_T = 6;
  public static final int DO = 12;
  public static final int INTEGER_LITERAL = 52;
  public static final int IDENTIFIER = 51;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT_T",
  "FLOAT_T",
  "BOOL_T",
  "CHAR_T",
  "STRING_T",
  "SCIENTIFIC_T",
  "FRAC_T",
  "EMPTY_T",
  "IF",
  "ELSE",
  "DO",
  "WHILE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "RETURN",
  "BREAK",
  "CIN",
  "COUT",
  "TRUE",
  "FALSE",
  "MAIN",
  "EQUAL",
  "N_EQUAL",
  "LESS_T",
  "LESS_TE",
  "GREATHER_T",
  "GREATHER_TE",
  "TILDE",
  "ASSIGN",
  "PIPE_L",
  "PIPE_R",
  "BLOCK_OPEN",
  "BLOCK_CLOSE",
  "INDEX_OPEN",
  "INDEX_CLOSE",
  "BANG",
  "COMMA",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "MOD",
  "POW",
  "INC",
  "DEC",
  "AND",
  "OR",
  "NOT",
  "IDENTIFIER",
  "INTEGER_LITERAL",
  "FLOAT_LITERAL",
  "SCIENTIFIC_LITERAL",
  "FRACTION_LITERAL",
  "CHAR_LITERAL",
  "STRING_LITERAL"
  };
}

